# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:
  drupal:
    build: .
    image: custom-drupal
    ports:
      - 8080:80
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
