# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports:
      - 8080:80
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql-pw

volumes:
  drupal-data:

secrets:
  psql-pw:
    external: true
